export const mela_json_schema = {
        title: "JSON Mode",
        type: "json_schema",
        json_schema: {
          type: "object",
          properties: {
            id: { type: "string" },
            title: { type: "string" },
            text: { type: "string" },
            images: { type: "array", items: { type: "string" } },
            categories: { type: "array", items: { type: "string" } },
            yield: { type: "string" },
            prepTime: { type: "string" },
            cookTime: { type: "string" },
            totalTime: { type: "string" },
            ingredients: { type: "string" },
            instructions: { type: "string" },
            notes: { type: "string" },
            nutrition: { type: "string" },
            link: { type: "string" },
            favorite: { type: "boolean" },
            wantToCook: { type: "boolean" },
            date: { type: "string" },
          },
          required: [
            "title",
            "ingredients",
            "instructions",
            "yield",
            "id",
            "favorite",
            "wantToCook",
            "notes",
            "categories",
            "date",
            "link",
            "images"
          ]
        },
      }